#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := project_template

include $ ~/esp/ESP8266_RTOS_SDK/make/project.mk

